# fly.toml app configuration file generated for oilmoguls.com
app = "oil-moguls"
primary_region = "lhr"

[build]

[env]
  PHX_HOST = "oilmoguls.com"
  PHX_CHECK_ORIGINS = "www.oilmoguls.com"
  PHX_SERVER = "true"
  PORT = "8080"
  APEXBEE_URL = "https://apexbee.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
