defmodule OilMogulsWeb.HomeLive do
  use OilMogulsWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :page_title, "Home")}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <section class="om-hero-mesh relative overflow-hidden">
      <div class="om-container relative z-10 grid gap-12 py-16 sm:py-20 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)] lg:items-end lg:py-28">
        <div>
          <p class="om-eyebrow om-eyebrow-light">Learning community · not an oil company</p>
          <h1 class="om-display om-display-light mt-6 max-w-3xl text-4xl sm:text-5xl lg:text-6xl">
            The learning community for oil and gas professionals.
          </h1>
          <p class="mt-6 max-w-xl text-base leading-relaxed text-offwhite/75 sm:text-lg">
            We do not drill, produce, or operate assets. Oil Moguls is where students, graduates, engineers, and the rest of the sector's serious professionals build skills, relationships, and access.
          </p>
          <div class="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center">
            <.link navigate="/join" class="om-btn om-btn-sage">Join the community</.link>
            <.link navigate="/audiences" class="om-btn om-btn-ghost">See who it's for</.link>
          </div>
        </div>

        <aside class="border border-white/10 bg-night/40 p-6 sm:p-8">
          <p class="font-mono text-xs tracking-[0.18em] uppercase text-sage">Member outcomes</p>
          <p class="mt-4 font-mono text-4xl font-medium text-offwhite sm:text-5xl">₦1B+</p>
          <p class="mt-2 text-sm leading-relaxed text-offwhite/70">
            Traceable opportunities generated by members in the first three months.
          </p>
          <div class="mt-8 grid grid-cols-2 gap-6">
            <.proof_stat value="13" label="Audiences we exist to serve" />
            <.proof_stat value="ApexBee" label="Our practice product, built in-house" />
          </div>
        </aside>
      </div>
    </section>

    <section class="border-b border-line bg-white">
      <div class="om-container grid gap-8 py-10 sm:grid-cols-3 sm:gap-12">
        <p class="text-sm leading-relaxed text-muted">
          Not an operator. Not a service company. Not a recruitment agency.
        </p>
        <p class="sm:col-span-2 text-base leading-relaxed text-night sm:text-lg">
          Oil Moguls is a learning community with digital tools around it: Academy, ApexBee, mentorship, a verified opportunity board, and a professional network with standards.
        </p>
      </div>
    </section>

    <section class="py-16 sm:py-24">
      <div class="om-container">
        <.section_heading kicker="What we build" title="Community first. Products that serve it.">
          Learning on its own is not enough. It needs somewhere to connect to practice, people, and opportunity.
        </.section_heading>

        <div class="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <.feature_card icon="hero-academic-cap" title="Oil Moguls Academy">
            Structured courses for the skills the field actually hires for, taught the way working professionals work.
          </.feature_card>
          <.feature_card icon="hero-cpu-chip" title="ApexBee">
            Our practice product. Exam-ready drills, progress you can see, and programmes built for oil and gas professionals.
          </.feature_card>
          <.feature_card icon="hero-user-group" title="Mentorship & community">
            Verified mentors and peers. A network on competence, not on who you already know.
          </.feature_card>
          <.feature_card icon="hero-clipboard-document-check" title="Opportunity Board">
            Vetted roles and introductions for members. We platform opportunity. We do not employ the industry.
          </.feature_card>
          <.feature_card icon="hero-microphone" title="Conference">
            The flagship gathering: learn, connect, and get seen in the same room.
          </.feature_card>
          <.feature_card icon="hero-sparkles" title="Incubator">
            The path that develops the next leaders of the community itself, so the standard scales.
          </.feature_card>
        </div>
      </div>
    </section>

    <section class="bg-forest py-16 text-offwhite sm:py-24">
      <div class="om-container grid gap-12 lg:grid-cols-2 lg:items-center">
        <div>
          <p class="om-eyebrow om-eyebrow-light">A product of Oil Moguls</p>
          <h2 class="om-display om-display-light mt-5 text-3xl sm:text-4xl">ApexBee</h2>
          <p class="mt-4 max-w-xl text-offwhite/75">
            Practice is where competence is proven. ApexBee is the Oil Moguls product for drills, exam readiness, and tracked progress, so a course does not end when the slides do.
          </p>
          <div class="mt-8 flex flex-col gap-3 sm:flex-row">
            <.link
              href={OilMoguls.apexbee_url()}
              target="_blank"
              rel="noopener noreferrer"
              class="om-btn om-btn-sage"
            >
              Launch ApexBee
            </.link>
            <.link navigate="/apexbee" class="om-btn om-btn-ghost">How it fits</.link>
          </div>
        </div>
        <ul class="space-y-5 text-sm text-offwhite/80">
          <li class="border-t border-white/10 pt-5">Structured practice for professional programmes in oil and gas, leadership, HSE, and regulation.</li>
          <li class="border-t border-white/10 pt-5">Progress you can see: coverage, weak spots, and the next drill worth doing.</li>
          <li class="border-t border-white/10 pt-5">Built for members of this community, not sold as a generic quiz app.</li>
        </ul>
      </div>
    </section>

    <section class="py-16 sm:py-24">
      <div class="om-container">
        <.section_heading kicker="Who it's for" title="Thirteen audiences. One community.">
          From the final-year student to the regulator. Oil Moguls is built for people in and around oil and gas careers, not as an oil and gas company itself.
        </.section_heading>

        <div class="mt-12 grid gap-px overflow-hidden rounded-sm border border-line bg-line sm:grid-cols-2 lg:grid-cols-3">
          <div :for={persona <- OilMoguls.Audiences.all()} class="bg-offwhite p-6 sm:p-8">
            <p class="font-semibold text-forest">{persona.name}</p>
            <p class="om-body mt-3 text-sm">{persona.body}</p>
          </div>
        </div>
        <div class="mt-8">
          <.link navigate="/audiences" class="om-btn om-btn-outline">How each audience uses Oil Moguls</.link>
        </div>
      </div>
    </section>

    <section class="border-y border-line bg-white py-16 sm:py-24">
      <div class="om-container">
        <.section_heading kicker="How it works" title="Learn. Practise. Get into the room.">
          Competence first. Access follows. The community, ApexBee, mentors, and the board exist to move skill into real work.
        </.section_heading>

        <ol class="mt-12 grid gap-8 lg:grid-cols-3">
          <li :for={{step, index} <- Enum.with_index(steps(), 1)} class="flex gap-4">
            <span class="font-mono text-sm text-sage">{String.pad_leading("#{index}", 2, "0")}</span>
            <div>
              <h3 class="font-semibold text-forest">{step.title}</h3>
              <p class="om-body mt-2 text-sm">{step.body}</p>
            </div>
          </li>
        </ol>
      </div>
    </section>

    <section class="om-hero-mesh py-16 sm:py-24">
      <div class="om-container flex flex-col items-start gap-6 lg:flex-row lg:items-end lg:justify-between">
        <div class="max-w-xl">
          <p class="om-eyebrow om-eyebrow-light">Next step</p>
          <h2 class="om-display om-display-light mt-5 text-3xl sm:text-4xl">
            Your career should not depend on who you happen to know.
          </h2>
          <p class="mt-4 text-offwhite/70">
            Join as a member of the community. Whether you are a student, an engineer, a trainer, or a regulator, this is the same door.
          </p>
        </div>
        <div class="flex flex-col gap-3 sm:flex-row">
          <.link navigate="/join" class="om-btn om-btn-sage">Request access</.link>
          <.link navigate="/about" class="om-btn om-btn-ghost">Read the story</.link>
        </div>
      </div>
    </section>
    """
  end

  defp steps do
    [
      %{title: "Learn the skill", body: "Academy tracks designed for real oil and gas work, not generic professional development."},
      %{title: "Practise until it holds", body: "ApexBee turns sitting through content into exam-ready, job-ready competence."},
      %{title: "Enter the room", body: "Mentors, peers, Conference, and a verified opportunity board, because knowing is not the same as access."}
    ]
  end
end
