<template>
  <section ref="hero" class="om-page-hero om-hero-mesh relative overflow-hidden">
    <HeroOrbs />
    <div class="om-container relative z-10 grid gap-10 py-12 sm:gap-12 sm:py-20 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)] lg:items-end lg:py-28">
      <div>
        <p class="om-eyebrow om-eyebrow-light om-hero-kicker">Learning community · not an oil company</p>
        <SplitHeading
          class="om-display om-display-light mt-6 max-w-3xl text-[1.85rem] sm:text-5xl lg:text-6xl"
          text="The learning community for oil and gas professionals."
        />
        <p class="om-hero-copy mt-6 max-w-xl text-base leading-relaxed text-offwhite/75 sm:text-lg">
          We do not drill, produce, or operate assets. Oil Moguls is where students, graduates, engineers, and the rest of the sector's serious professionals build skills, relationships, and access.
        </p>
        <div class="om-hero-copy om-hero-copy-late mt-8 flex flex-col gap-3 sm:flex-row sm:items-center">
          <RouterLink to="/join" class="om-btn om-btn-sage">Join the community</RouterLink>
          <RouterLink to="/audiences" class="om-btn om-btn-ghost">See who it's for</RouterLink>
        </div>
      </div>
      <aside class="om-proof border border-white/10 bg-night/40 p-6 sm:p-8">
        <p class="font-mono text-xs tracking-[0.18em] uppercase text-sage">Member outcomes</p>
        <p class="mt-4 font-mono text-4xl font-medium text-offwhite sm:text-5xl">
              <CountUp prefix="₦" :value="1" suffix="B+" :decimals="1" :duration="1800" :delay="480" />
        </p>
        <p class="mt-2 text-sm leading-relaxed text-offwhite/70">
          Traceable opportunities generated by members in the first three months.
        </p>
        <div class="mt-8 grid grid-cols-2 gap-6">
          <div class="border-t border-white/15 pt-5">
            <p class="font-mono text-2xl font-medium text-sage sm:text-3xl">
              <CountUp :value="13" :duration="1600" :delay="620" />
            </p>
            <p class="mt-2 text-sm text-offwhite/70">Audiences we exist to serve</p>
          </div>
          <div class="border-t border-white/15 pt-5">
            <p class="font-mono text-2xl font-medium text-sage sm:text-3xl">ApexBee</p>
            <p class="mt-2 text-sm text-offwhite/70">Our practice product, built in-house</p>
          </div>
        </div>
      </aside>
    </div>
  </section>

  <section class="border-b border-line bg-white">
    <div class="om-container grid gap-8 py-10 sm:grid-cols-3 sm:gap-12">
      <p class="text-sm leading-relaxed text-muted">Not an operator. Not a service company. Not a recruitment agency.</p>
      <p class="sm:col-span-2 text-base leading-relaxed text-night sm:text-lg">
        Oil Moguls is a learning community with digital tools around it: Academy, ApexBee, mentorship, a verified opportunity board, and a professional network with standards.
      </p>
    </div>
  </section>

  <section class="py-16 sm:py-24">
    <div class="om-container">
      <SectionHeading kicker="What we build" title="Community first. Products that serve it.">
        Learning on its own is not enough. It needs somewhere to connect to practice, people, and opportunity.
      </SectionHeading>
      <div class="om-media-grid mt-12">
        <FeatureCard
          v-for="card in features"
          :key="card.title"
          :title="card.title"
          :mark="card.mark"
          :image="card.image"
          :to="card.to"
        >
          {{ card.body }}
        </FeatureCard>
      </div>
    </div>
  </section>

  <section class="bg-forest py-16 text-offwhite sm:py-24">
    <div class="om-container grid gap-12 lg:grid-cols-2 lg:items-center">
      <div>
        <p class="om-eyebrow om-eyebrow-light">A product of Oil Moguls</p>
        <h2 class="om-display om-display-light mt-5 text-3xl sm:text-4xl">ApexBee</h2>
        <p class="mt-4 max-w-xl text-offwhite/75">
          Practice is where competence is proven. ApexBee is the Oil Moguls product for drills, exam readiness, and tracked progress, so a course does not end when the slides do.
        </p>
        <div class="mt-8 flex flex-col gap-3 sm:flex-row">
          <a :href="APEXBEE_URL" class="om-btn om-btn-sage" target="_blank" rel="noopener noreferrer">Launch ApexBee</a>
          <RouterLink to="/apexbee" class="om-btn om-btn-ghost">How it fits</RouterLink>
        </div>
      </div>
      <ul class="space-y-5 text-sm text-offwhite/80">
        <li class="border-t border-white/10 pt-5">Structured practice for professional programmes in oil and gas, leadership, HSE, and regulation.</li>
        <li class="border-t border-white/10 pt-5">Progress you can see: coverage, weak spots, and the next drill worth doing.</li>
        <li class="border-t border-white/10 pt-5">Built for members of this community, not sold as a generic quiz app.</li>
      </ul>
    </div>
  </section>

  <section class="py-16 sm:py-24">
    <div class="om-container">
      <SectionHeading kicker="Who it's for" title="Thirteen audiences. One community.">
        From the final-year student to the regulator. Oil Moguls is built for people in and around oil and gas careers, not as an oil and gas company itself.
      </SectionHeading>
      <div class="om-media-grid mt-12">
        <FeatureCard
          v-for="persona in audiences"
          :key="persona.name"
          :title="persona.name"
          mark="Audience"
          :image="persona.image"
          to="/audiences"
        >
          {{ persona.body }}
        </FeatureCard>
      </div>
      <div class="mt-8">
        <RouterLink to="/audiences" class="om-btn om-btn-outline">How each audience uses Oil Moguls</RouterLink>
      </div>
    </div>
  </section>

  <section class="border-y border-line bg-white py-16 sm:py-24">
    <div class="om-container">
      <SectionHeading kicker="How it works" title="Learn. Practise. Get into the room.">
        Competence first. Access follows. The community, ApexBee, mentors, and the board exist to move skill into real work.
      </SectionHeading>
      <ol class="mt-12 grid gap-8 lg:grid-cols-3">
        <li v-for="(step, index) in steps" :key="step.title" class="om-step flex gap-4">
          <span class="font-mono text-sm text-sage">{{ String(index + 1).padStart(2, "0") }}</span>
          <div>
            <h3 class="font-semibold text-forest">{{ step.title }}</h3>
            <p class="om-body mt-2 text-sm">{{ step.body }}</p>
          </div>
        </li>
      </ol>
    </div>
  </section>

  <section class="om-hero-mesh relative overflow-hidden py-16 sm:py-24">
    <HeroOrbs />
    <div class="om-container relative z-10 flex flex-col items-start gap-6 lg:flex-row lg:items-end lg:justify-between">
      <div class="max-w-xl">
        <p class="om-eyebrow om-eyebrow-light">Next step</p>
        <h2 class="om-display om-display-light mt-5 text-3xl sm:text-4xl">Your career should not depend on who you happen to know.</h2>
        <p class="mt-4 text-offwhite/70">
          Join as a member of the community. Whether you are a student, an engineer, a trainer, or a regulator, this is the same door.
        </p>
      </div>
      <div class="flex flex-col gap-3 sm:flex-row">
        <RouterLink to="/join" class="om-btn om-btn-sage">Request access</RouterLink>
        <RouterLink to="/about" class="om-btn om-btn-ghost">Read the story</RouterLink>
      </div>
    </div>
  </section>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { RouterLink } from "vue-router";
import CountUp from "../components/CountUp.vue";
import FeatureCard from "../components/FeatureCard.vue";
import HeroOrbs from "../components/HeroOrbs.vue";
import SectionHeading from "../components/SectionHeading.vue";
import SplitHeading from "../components/SplitHeading.vue";
import { APEXBEE_URL, audiences } from "../content";

const hero = ref(null);
onMounted(() => {
  requestAnimationFrame(() => {
    hero.value?.classList.add("is-live");
  });
});

const features = [
  { mark: "01", title: "Oil Moguls Academy", body: "Structured courses for the skills the field actually hires for, taught the way working professionals work.", image: "/cards/card-academy.jpg", to: "/academy" },
  { mark: "02", title: "ApexBee", body: "Our practice product. Exam-ready drills, progress you can see, and programmes built for oil and gas professionals.", image: "/cards/card-apexbee.jpg", to: "/apexbee" },
  { mark: "03", title: "Mentorship & community", body: "Verified mentors and peers. A network on competence, not on who you already know.", image: "/cards/card-mentorship.jpg", to: "/community" },
  { mark: "04", title: "Opportunity Board", body: "Vetted roles and introductions for members. We platform opportunity. We do not employ the industry.", image: "/cards/card-opportunity.jpg", to: "/opportunities" },
  { mark: "05", title: "Conference", body: "The flagship gathering: learn, connect, and get seen in the same room.", image: "/cards/card-conference.jpg", to: "/conference" },
  { mark: "06", title: "Incubator", body: "The path that develops the next leaders of the community itself, so the standard scales.", image: "/cards/card-incubator.jpg", to: "/join" },
];

const steps = [
  { title: "Learn the skill", body: "Academy tracks designed for real oil and gas work, not generic professional development." },
  { title: "Practise until it holds", body: "ApexBee turns sitting through content into exam-ready, job-ready competence." },
  { title: "Enter the room", body: "Mentors, peers, Conference, and a verified opportunity board, because knowing is not the same as access." },
];
</script>
